# Generated by Django 6.0.2 on 2026-02-21 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Project Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon_class', models.CharField(blank=True, help_text="Font Awesome or Devicon class (e.g., 'fab fa-python')", max_length=100)),
                ('color', models.CharField(default='#6c757d', help_text='Hex color code for the technology badge', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(help_text='Brief description for project cards')),
                ('content', models.TextField(help_text='Detailed description for project detail page')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('planned', 'Planned')], default='completed', max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('featured', models.IntegerField(choices=[(0, 'Not Featured'), (1, 'Featured'), (2, 'Main Featured')], default=0)),
                ('live_url', models.URLField(blank=True, help_text='Link to live demo')),
                ('github_url', models.URLField(blank=True, help_text='Link to GitHub repository')),
                ('documentation_url', models.URLField(blank=True)),
                ('thumbnail', models.ImageField(help_text='Main project image for cards', upload_to='projects/thumbnails/')),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('project_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, help_text="e.g., '3 months'", max_length=100)),
                ('challenges', models.TextField(blank=True, help_text='Challenges faced during development')),
                ('solutions', models.TextField(blank=True, help_text='Solutions implemented')),
                ('architecture', models.TextField(blank=True, help_text='Technical architecture description')),
                ('key_features', models.TextField(blank=True, help_text='Key features (one per line)')),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.projectcategory')),
                ('technologies', models.ManyToManyField(blank=True, related_name='projects', to='projects.technology')),
            ],
            options={
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project')),
            ],
            options={
                'ordering': ['order', '-is_featured'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('icon_class', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'Project Stats',
                'ordering': ['order'],
            },
        ),
    ]
